In [186]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [187]:
df=pd.read_excel("GAMEnew.xlsx")

In [188]:
x1 = df.platform

In [189]:
x1

0         7
1         7
2         7
3         7
4         7
         ..
16591     1
16592    17
16593    16
16594    22
16595     4
Name: platform, Length: 16596, dtype: int64

In [190]:
from tensorflow.keras.utils import to_categorical

In [191]:
x1 = to_categorical(x1, 31)

In [192]:
x1[1]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [193]:
x2 = df.Genre

In [194]:
x2 = to_categorical(x2, 13)

In [195]:
x2[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)

In [196]:
x3 = df.Publisher

In [197]:
x3 = to_categorical(x3, 572)

In [198]:
 x=np.concatenate((x1,x2,x3 ), axis=1)

In [199]:
x.shape

(16596, 616)

In [200]:
df2=pd.read_excel("ynew.xlsx")

In [201]:
df2=round(df2/4)

In [202]:
df2

Global_Sales
0               0.0
1               0.0
2               0.0
3               0.0
4               0.0
...             ...
16591           0.0
16592           0.0
16593           0.0
16594           0.0
16595           0.0

[16596 rows x 1 columns]

In [203]:
y=df2.values

In [204]:
y[15875]

array([7.])

In [205]:
y = to_categorical(y,11)

In [206]:
y[15877]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [207]:
x_train=x[0:13500]
y_train=y[0:13500]
x_test=x[13500:]
y_test=y[13500:]

In [208]:
x_test.shape

(3096, 616)

In [209]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [214]:
models=Sequential()
models.add(Dense(50,input_dim=616,activation='relu'))
models.add(Dense(11,activation='softmax'))

In [215]:
models.compile(loss='mse',optimizer=SGD(lr=1),metrics=['accuracy'])

In [216]:
models.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_20 (Dense)             (None, 50)                30850     
_________________________________________________________________
dense_21 (Dense)             (None, 11)                561       
Total params: 31,411
Trainable params: 31,411
Non-trainable params: 0
_________________________________________________________________


In [217]:
models.fit(x_train, y_train, batch_size=5, epochs=10)

Train on 13500 samples
Epoch 1/10
13500/13500 [==============================] - 5s 352us/sample - loss: 0.0097 - accuracy: 0.9474
Epoch 2/10
13500/13500 [==============================] - 5s 378us/sample - loss: 0.0085 - accuracy: 0.9481 - loss: 0.0085 - accuracy: 0.
Epoch 3/10
13500/13500 [==============================] - 4s 322us/sample - loss: 0.0084 - accuracy: 0.9481
Epoch 4/10
13500/13500 [==============================] - 4s 329us/sample - loss: 0.0083 - accuracy: 0.9482
Epoch 5/10
13500/13500 [==============================] - 5s 339us/sample - loss: 0.0083 - accuracy: 0.9479
Epoch 6/10
13500/13500 [==============================] - 4s 311us/sample - loss: 0.0082 - accuracy: 0.9479
Epoch 7/10
13500/13500 [==============================] - 5s 334us/sample - loss: 0.0082 - accuracy: 0.9479
Epoch 8/10
13500/13500 [==============================] - 5s 366us/sample - loss: 0.0082 - accuracy: 0.9481
Epoch 9/10
13500/13500 [==============================] - 4s 328us/sample - loss: 0

In [239]:
result = models.predict_classes(x_test)

In [240]:
#print('神經網路預測是:', result)

In [241]:
for i in result:
    print (i)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [224]:
result.shape

(3096,)

In [230]:
score = models.evaluate(x_test, y_test)

3096/3096 [==============================] - 0s 82us/sample - loss: 0.0076 - accuracy: 0.9522


In [231]:
loss, acc = score

In [232]:
print('測試資料的正確率為', acc)

測試資料的正確率為 0.95219636
