In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [3]:
df=pd.read_excel("GAMEnew.xlsx")

In [4]:
df

platform  Genre  Publisher  NA_Sales
0             7     11        326      0.65
1             7      4         26      0.00
2             7      4         26      0.11
3             7      4         26      0.00
4             7      4         26      0.00
...         ...    ...        ...       ...
16591         1      6         34      0.14
16592        17      6         34      0.17
16593        16     10        548      0.00
16594        22     12        326      0.00
16595         4      2         13      0.00

[16596 rows x 4 columns]

In [5]:
df=df.values

In [286]:
df

array([[7.00e+00, 1.10e+01, 3.26e+02, 6.50e-01],
       [7.00e+00, 4.00e+00, 2.60e+01, 0.00e+00],
       [7.00e+00, 4.00e+00, 2.60e+01, 1.10e-01],
       ...,
       [1.60e+01, 1.00e+01, 5.48e+02, 0.00e+00],
       [2.20e+01, 1.20e+01, 3.26e+02, 0.00e+00],
       [4.00e+00, 2.00e+00, 1.30e+01, 0.00e+00]])

In [287]:
df2=pd.read_excel("ynew.xlsx")

In [288]:
df2=df2.values

In [289]:
df2

array([[1.  ],
       [0.17],
       [0.23],
       ...,
       [0.02],
       [0.05],
       [0.14]])

In [290]:
x_train=df

In [291]:
len(x_train)

16596

In [292]:
y_train=df2

In [293]:
len(y_train)

16596

In [294]:
x_train=df[0:13500]
y_train=df2[0:13500]
x_test=df[13500:]
y_test=df2[13500:]

In [295]:
len(x_train)

13500

In [296]:
len(x_test)

3096

In [297]:
len(y_train)

13500

In [298]:
len(y_test)

3096

In [299]:
x_train[9487]

array([5.  , 3.  , 8.  , 0.18])

In [300]:
y_train=y_train/82.74

array([0.44])

In [301]:
x_train.shape

(13500, 4)

In [302]:
y_train.shape

(13500, 1)

In [303]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [304]:
from tensorflow.keras import backend as K #转换为张量
x_train= K.cast_to_floatx(x_train)
y_train = K.cast_to_floatx(y_train)

In [309]:
models=Sequential()
models.add(Dense(50,input_dim=4,activation='relu'))
models.add(Dense(50,activation='relu'))
models.add(Dense(50,activation='relu'))
models.add(Dense(50,activation='relu'))
models.add(Dense(50,activation='relu'))
models.add(Dense(50,activation='relu'))
models.add(Dense(10,activation='sigmoid'))

In [310]:
models.compile(loss='mae',optimizer=SGD(lr=1),metrics=['accuracy'])

In [311]:
models.summary()

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_108 (Dense)            (None, 50)                250       
_________________________________________________________________
dense_109 (Dense)            (None, 50)                2550      
_________________________________________________________________
dense_110 (Dense)            (None, 50)                2550      
_________________________________________________________________
dense_111 (Dense)            (None, 50)                2550      
_________________________________________________________________
dense_112 (Dense)            (None, 50)                2550      
_________________________________________________________________
dense_113 (Dense)            (None, 50)                2550      
_________________________________________________________________
dense_114 (Dense)            (None, 10)              

In [312]:
models.fit(x_train, y_train, batch_size=5, epochs=10)

Train on 13500 samples
Epoch 1/10
13500/13500 [==============================] - 6s 414us/sample - loss: 0.4625 - accuracy: 0.0553
Epoch 2/10
13500/13500 [==============================] - 5s 374us/sample - loss: 0.4685 - accuracy: 0.0815
Epoch 3/10
13500/13500 [==============================] - 5s 377us/sample - loss: 0.6322 - accuracy: 0.6711
Epoch 4/10
13500/13500 [==============================] - 5s 387us/sample - loss: 0.6728 - accuracy: 0.7997
Epoch 5/10
13500/13500 [==============================] - 6s 475us/sample - loss: 0.5062 - accuracy: 0.1758
Epoch 6/10
13500/13500 [==============================] - 6s 408us/sample - loss: 0.7565 - accuracy: 0.9993
Epoch 7/10
13500/13500 [==============================] - 6s 414us/sample - loss: 0.7566 - accuracy: 1.0000
Epoch 8/10
13500/13500 [==============================] - 6s 434us/sample - loss: 0.7566 - accuracy: 1.0000
Epoch 9/10
13500/13500 [==============================] - 6s 412us/sample - loss: 0.7566 - accuracy: 1.0000
Epoch

In [313]:
type(x_test)

numpy.ndarray

In [314]:
from tensorflow.keras import backend as K #转换为张量
y_test = K.cast_to_floatx(y_test)

In [315]:
x_test = K.cast_to_floatx(x_test)

In [316]:
result = models.predict_classes(x_test)

In [7]:
n = 15875
print('神經網路預測是:', result[n],result[n]*4)

NameError: name 'result' is not defined